{
 "title": "917 Business View (Beta)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1 style=\"font-size: 4rem; color: #05a6fc\"><b>917 Business View</h1></b></center>\r\n"
   },
   "targets": [
    {
     "expr": "sum(count_over_time({operationName=\"GetRewardsPoints\"} [$__range]))"
    }
   ]
  },
  {
   "title": "917 Campaign Performance - Optimized",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "LOGIN  / REGISTRATIONS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 1, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=~\"RefreshUserTokenV3\", channel=\"SUPERAPP\", feature_Login=\"true\", pushserver=\"lambda-promtail-prod\"} [$__range]))",
       "legendFormat": "count"
      },
      {}
     ]
    },
    {
     "title": "Failed Login - SysErr",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 5, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "Failed Login - SubErr",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "MARKETPLACE REDEMPTION ",
     "type": "stat",
     "description": "Overall NG1* Dashboard Access Count",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=~\"RedeemLoyaltyRewards\", channel=\"SUPERAPP\", feature_Rewards_Redeem=\"true\", pushserver=\"lambda-promtail-prod\"} [$__range]))"
      }
     ]
    },
    {
     "title": "Failed Redeem-SysErr",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 17, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A+$B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "Failed Redeem-SubErr",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A+$B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "RAFFLE REDEMPTIONS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=~\"CheckCompleteKYC\", channel=\"SUPERAPP\", pushserver=\"lambda-promtail-prod\"} [$__range]))",
       "legendFormat": "count"
      },
      {}
     ]
    },
    {
     "title": "Failed Redeem-SysErr",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 17, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"CheckCompleteKYC\"} [$__range]))",
       "legendFormat": "A"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"CheckCompleteKYC\", status=\"500\"} [$__range]))",
       "legendFormat": "B"
      },
      { "expression": "($B/$A)*100", "type": "math" }
     ]
    },
    {
     "title": "Failed Redeem-SubErr",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 20, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "($B/$A)*100", "type": "math" }
     ]
    },
    {
     "title": "GLOBEONE HEALTH",
     "type": "stat",
     "description": "Overall NG1* Dashboard Access Count",
     "gridPos": { "h": 7, "w": 4, "x": 1, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"GetRegisteredUser\", feature_Dashboard=\"true\", pushserver=\"lambda-promtail-prod\"} [$__range]))"
      }
     ]
    },
    {
     "title": "Health - SysErr",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 5, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "Health-SubErr",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Login / Registrations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transactions",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=~\"RefreshUserTokenV3\", channel=\"SUPERAPP\", feature_Login=\"true\", pushserver=\"lambda-promtail-prod\"} [$__range]))",
       "legendFormat": "count"
      },
      {}
     ]
    },
    {
     "title": "Success Rate ",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 5, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"RefreshUserTokenV3\", status=~\"401|500|200\", feature_Login=\"true\", pushserver=\"lambda-promtail-prod\"} [$__range]))",
       "legendFormat": "A"
      },
      {
       "expr": "sum(count_over_time({operationName=\"RefreshUserTokenV3\", channel=\"SUPERAPP\", status=\"200\", feature_Login=\"true\", pushserver=\"lambda-promtail-prod\"} [$__range]))",
       "legendFormat": "B"
      }
     ]
    },
    {
     "title": "True Success Rate (SysErr) and Transaction Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 12 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"RefreshUserTokenV3\", status=\"500\"} [$__range]))",
       "legendFormat": "B"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"RefreshUserTokenV3\", status=\"200\"} [$__range]))",
       "legendFormat": "count"
      },
      { "expression": "$A+$B", "type": "math" },
      { "expression": "($A/$C)*100", "type": "math" }
     ]
    },
    {
     "title": "Success vs. SubErr (Transaction Count)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 18 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", status=~\"200\", operationName=\"RefreshUserTokenV3\"} [$__range]))",
       "legendFormat": "count"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", status=~\"401\", operationName=\"RefreshUserTokenV3\"} [$__range]))",
       "legendFormat": "B"
      },
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$C)*100", "type": "math" }
     ]
    },
    {
     "title": "SysErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 5, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "SubErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 7, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "($B/$A)*100", "type": "math" }
     ]
    },
    {
     "title": "Impacted Subscribers Due To Error",
     "type": "table",
     "description": "The Logs can be copied and shared to the technical team for further investigation",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "{status=~\"400|401|404|403|405|409|500\", operationName=~\"RefreshUserTokenV3\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "GlobeOne Mobile App Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transactions",
     "type": "stat",
     "description": "Overall NG1* Dashboard Access Count",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=\"GetRegisteredUser\", channel=\"SUPERAPP\"} [$__range]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Success Rate ",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 5, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"GetRegisteredUser\"} [$__range]))",
       "legendFormat": "A"
      },
      {
       "expr": "sum(count_over_time({operationName=\"GetRegisteredUser\", channel=\"SUPERAPP\", status=\"200\"} [$__range]))",
       "legendFormat": "B"
      }
     ]
    },
    {
     "title": "True Success Rate (SysErr) and Transaction Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 13 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"GetRegisteredUser\"} [$__range]))"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"GetRegisteredUser\", status=\"200\"} [$__range]))",
       "legendFormat": "count"
      },
      { "expression": "($A/$B)*100", "type": "math" }
     ]
    },
    {
     "title": "SysErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 5, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"GetRegisteredUser\", status=~\"50001|500\"} [$__range]))",
       "legendFormat": "A"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"GetRegisteredUser\"} [$__range]))",
       "legendFormat": "B"
      },
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "SubErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 7, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"GetRegisteredUser\", status=\"400\"} [$__range]))"
      },
      { "expression": "($B/$A)*100", "type": "math" }
     ]
    },
    {
     "title": "Success vs. SubErr (Transaction Count)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 20 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", status=~\"200\", operationName=\"GetRegisteredUser\"} [$__range]))",
       "legendFormat": "count"
      },
      {
       "expr": "sum(count_over_time({operationName=\"GetRegisteredUser\", channel=\"SUPERAPP\"} [$__range]))"
      },
      { "expression": "($A/$B)*100", "type": "math" }
     ]
    },
    {
     "title": "Impacted Subscribers Due To Error",
     "type": "table",
     "description": "The Logs can be copied and shared to the technical team for further investigation",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "{status=~\"400|401|404|403|405|409|500\", operationName=~\"GetRegisteredUser|GetAccountDetails|GetBillingDetails-v3|GetPlanDetails-v3|GetAccountBarringInfo|GetUsageConsumptionReports-v4\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raffle Redemptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transactions",
     "type": "stat",
     "description": "Overall NG1* Dashboard Access Count",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=\"CheckCompleteKYC\", channel=\"SUPERAPP\"} [$__range]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Success Rate ",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 5, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"CheckCompleteKYC\"} [$__range]))",
       "legendFormat": "A"
      },
      {
       "expr": "sum(count_over_time({operationName=\"CheckCompleteKYC\", channel=\"SUPERAPP\", status=\"200\"} [$__range]))",
       "legendFormat": "B"
      }
     ]
    },
    {
     "title": "True Success Rate (SysErr) and Transaction Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 14 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"CheckCompleteKYC\"} [$__range]))"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"CheckCompleteKYC\", status=\"200\"} [$__range]))",
       "legendFormat": "count"
      },
      { "expression": "($A/$B)*100", "type": "math" }
     ]
    },
    {
     "title": "Success vs. SubErr (Transaction Count)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 20 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", status=~\"200\", operationName=\"CheckCompleteKYC\"} [$__range]))",
       "legendFormat": "count"
      },
      {
       "expr": "sum(count_over_time({operationName=\"CheckCompleteKYC\", channel=\"SUPERAPP\"} [$__range]))"
      },
      { "expression": "($A/$B)*100", "type": "math" }
     ]
    },
    {
     "title": "SysErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 5, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"CheckCompleteKYC\", status=~\"50001|500\"} [$__range]))",
       "legendFormat": "A"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"CheckCompleteKYC\"} [$__range]))",
       "legendFormat": "B"
      },
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "SubErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 7, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"CheckCompleteKYC\", status=\"400\"} [$__range]))"
      },
      { "expression": "($B/$A)*100", "type": "math" }
     ]
    },
    {
     "title": "Impacted Subscribers Due To Error",
     "type": "table",
     "description": "The Logs can be copied and shared to the technical team for further investigation",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "{status=~\"400|401|404|403|405|409|500\", operationName=~\"CheckCompleteKYC\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Market Place Redemptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transactions",
     "type": "stat",
     "description": "Overall NG1* Dashboard Access Count",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=~\"RedeemLoyaltyRewards\"} [$__range]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Success Rate ",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 5, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"RedeemLoyaltyRewards\"} [$__range]))",
       "legendFormat": "A"
      },
      {
       "expr": "sum(count_over_time({operationName=\"RedeemLoyaltyRewards\", channel=\"SUPERAPP\", status=\"200\"} [$__range]))",
       "legendFormat": "B"
      }
     ]
    },
    {
     "title": "True Success Rate (SysErr) and Transaction Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 15 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"RedeemLoyaltyRewards\", status=\"500\"} [$__range]))",
       "legendFormat": "B"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"RedeemLoyaltyRewards\", status=\"200\"} [$__range]))",
       "legendFormat": "count"
      },
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$C)*100", "type": "math" }
     ]
    },
    {
     "title": "SysError",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 5, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"RedeemLoyaltyRewards\", status=\"500\"} [$__range]))"
      },
      { "expression": "($B/$A)*100", "type": "math" }
     ]
    },
    {
     "title": "SubErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 7, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"RedeemLoyaltyRewards\", status=\"400\"} [$__range]))"
      },
      { "expression": "($B/$A)*100", "type": "math" }
     ]
    },
    {
     "title": "Success vs. SubErr (Transaction Count)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 22 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", status=~\"200\", operationName=\"RedeemLoyaltyRewards\"} [$__range]))",
       "legendFormat": "count"
      },
      {
       "expr": "sum(count_over_time({operationName=\"RedeemLoyaltyRewards\", status=\"400\", channel=\"SUPERAPP\"} [$__range]))",
       "legendFormat": "B"
      },
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$C)*100", "type": "math" }
     ]
    },
    {
     "title": "Impacted Subscribers Due To Error",
     "type": "table",
     "description": "The Logs can be copied and shared to the technical team for further investigation",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "{status=~\"400|401|404|403|405|409|500\", operationName=~\"RedeemLoyaltyRewards\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Music Fest Redemptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transactions",
     "type": "stat",
     "description": "Overall NG1* Dashboard Access Count",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=\"RedeemLoyaltyRewards\"} [$__range]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Success Rate ",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 5, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"RedeemLoyaltyRewards\"} [$__range]))",
       "legendFormat": "A"
      },
      {
       "expr": "sum(count_over_time({operationName=\"RedeemLoyaltyRewards\", channel=\"SUPERAPP\", status=\"200\"} [$__range]))",
       "legendFormat": "B"
      }
     ]
    },
    {
     "title": "True Success Rate (SysErr) and Transaction Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 16 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"RedeemLoyaltyRewards\", status=\"500\"} [$__range]))",
       "legendFormat": "B"
      },
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=~\"RedeemLoyaltyRewards\", status=\"200\"} [$__range]))",
       "legendFormat": "count"
      },
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$C)*100", "type": "math" }
     ]
    },
    {
     "title": "SysErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 5, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$D)*100", "type": "math" }
     ]
    },
    {
     "title": "SubErr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 7, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", operationName=\"RedeemLoyaltyRewards\", status=\"400\"} [$__range]))"
      },
      { "expression": "($B/$A)*100", "type": "math" }
     ]
    },
    {
     "title": "Success vs. SubErr (Transaction Count)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 23 },
     "targets": [
      {
       "expr": "sum(count_over_time({channel=\"SUPERAPP\", status=~\"200\", operationName=\"RedeemLoyaltyRewards\"} [$__range]))",
       "legendFormat": "count"
      },
      {
       "expr": "sum(count_over_time({operationName=\"RedeemLoyaltyRewards\", status=\"400\", channel=\"SUPERAPP\"} [$__range]))",
       "legendFormat": "B"
      },
      { "expression": "$A + $B", "type": "math" },
      { "expression": "($A/$C)*100", "type": "math" }
     ]
    },
    {
     "title": "Impacted Subscribers Due To Error",
     "type": "table",
     "description": "The Logs can be copied and shared to the technical team for further investigation",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "{status=~\"400|401|404|403|405|409|500\", operationName=~\"RedeemLoyaltyRewards\"}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 39 },
     "options": {
      "content": "<b><h1 style=\"font-size: 1rem; color: #95d3f5\">c/o Shannah Aberin, Iggy Villanueva, Jorms Manalang</h1></b>\r\nThis dashboord mainly caters the business transactions, which will be used for data driven insights and analysis for each 917 Campaign"
     },
     "targets": [
      {
       "expr": "sum(count_over_time({operationName=\"GetRewardsPoints\"} [$__range]))"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 8 },
   "options": {
    "content": "<a style=\"font-size: 3rem; color: #05a6fc;\" href=\"https://globetelecom.atlassian.net/wiki/spaces/globeinfra/pages/4790747623/FAQ+s\">FAQ's</a>"
   }
  }
 ]
}